batch_size: 128
data_config: datafusion_churn_prediction_data.yaml
min_seq_len: 20
num_workers: 2
rnn_config:
  additional_params: null
  bidir: false
  category_emb_dim_reduction: 5
  hidden_state: 128
  num_layers: 1
  rnn_type: gru
splitter_params:
  cnt_max: 300
  cnt_min: 30
  split_count: 10
