batch_size: 128
data_config: rosbank_churn_prediction_data.yaml
min_seq_len: 20
num_workers: 2
rnn_config:
  category_emb_dim_reduction: 5
  hidden_state: 128
  rnn_type: rmt
splitter_params:
  cnt_max: 200
  cnt_min: 20
  split_count: 5
