batch_size: 10
data_config: rosbank_churn_prediction_data.yaml
num_workers: 2
rnn_config:
  additional_params:
    window: 1
  bidir: false
  category_emb_dim_reduction: 5
  hidden_state: 128
  num_layers: 1
  own_head: false
  rnn_type: qrnn
task:
  num_classes: 1
  objective: classification
