batch_size: 128
data_config: sberhack_gender_prediction_data.yaml
min_seq_len: 20
num_workers: 2
rnn_config:
  category_emb_dim_reduction: 5
  hidden_state: 64
  rnn_type: rmt
splitter_params:
  cnt_max: 1000
  cnt_min: 50
  split_count: 20
